UI/ViewComponents/MenuViewComponent.cs
using Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using UI.Models;

namespace UI.ViewComponents
{
    public class MenuViewComponent: ViewComponent
    {
        private IUserService _userService;

        public MenuViewComponent(IUserService userService)
        {
            _userService=userService;
        }

        public IViewComponentResult Invoke()
        {
            var claim = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier);
            MenuViewModel menuModel = new MenuViewModel();
            if (claim != null)
            {
                int userId = int.Parse(claim.Value);
                var result = _userService.GetById(userId);
                menuModel = new MenuViewModel()
                {
                    Name = result.Name,
                    Surname = result.Surname
                };
            }
            return View(menuModel);
        }
    }
}

UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Gutenberg</title>
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.css" rel="stylesheet">
</head>
<body>
    <div class="container-scroller">
        @await Component.InvokeAsync("Menu")
        <div class="container page-body-wrapper">
            <div class="main-panel">
                @RenderBody()
                <footer class="footer">
                    <div class="container-fluid d-flex justify-content-between">
                        <span class="text-muted d-block text-center text-sm-start d-sm-inline-block">Copyright © 2023</span>
                        <span class="float-none float-sm-end mt-1 mt-sm-0 text-end"> Project Gutenberg </span>
                    </div>
                </footer>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.8/datatables.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>